/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-11-20 06:36:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailSNS_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/stdLast/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/std_1st/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1570874896139L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"admin-dashboardUi/lib/bootstrap/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--Common Plugins CSS -->\r\n");
      out.write("<link href=\"admin-dashboardUi/css/plugins/plugins.css\" rel=\"stylesheet\">\r\n");
      out.write("<!--fonts-->\r\n");
      out.write("<link href=\"admin-dashboardUi/lib/line-icons/line-icons.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"admin-dashboardUi/lib/font-awesome/css/fontawesome-all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"admin-dashboardUi/lib/data-tables/dataTables.bootstrap4.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"admin-dashboardUi/lib/data-tables/responsive.bootstrap4.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"admin-dashboardUi/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Plugins CSS -->\r\n");
      out.write("<link href=\"css/plugins/plugins.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- REVOLUTION STYLE SHEETS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"revolution/css/settings.css\">\r\n");
      out.write("<!-- REVOLUTION LAYERS STYLES -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"revolution/css/layers.css\">\r\n");
      out.write("<!-- REVOLUTION NAVIGATION STYLES -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"revolution/css/navigation.css\">\r\n");
      out.write("<!-- load css for cubeportfolio -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"cubeportfolio/css/cubeportfolio.min.css\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#all_content {\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: 60% 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write("#img_section {\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write("#sns_section {\r\n");
      out.write("\tborder: 1px solid #999999;\r\n");
      out.write("\t/*background-color: blue;*/\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#scroll_section {\r\n");
      out.write("\toverflow: scroll;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("\theight: 70%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#picker_section {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\t/*background-color: green;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write("#picker_info1 {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#picker_info2 {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#w_picker_img1 {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\t/*background-color: yellow;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#w_picker_nick1 {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\t/*background-color: orange;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#w_picker_img2 {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\t/*background-color: yellow;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#w_picker_nick2 {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\t/*background-color: orange;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#a_follow {\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #4782d3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write("\r\n");
      out.write("#content_info {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-top: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_content{\r\n");
      out.write("\twidth: 98%; \r\n");
      out.write("\tborder: 0; \r\n");
      out.write("\tbackground: clear;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#write_date {\r\n");
      out.write("\tpadding-left: 60px;\r\n");
      out.write("\tcolor: #999999\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write("#reply_section {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tpadding-right: 10px;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write("#bottom_section{\r\n");
      out.write("\theight: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#icons{\r\n");
      out.write("\tdisplay: inline; \r\n");
      out.write("\tvertical-align: middle; \r\n");
      out.write("\tcolor: #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#howmanylikes{\r\n");
      out.write("\tvertical-align: super;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#btnLike{\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#reply_section{\r\n");
      out.write("\tpadding-right: 5px; \r\n");
      out.write("\tmargin-top: -10px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#new_reply_section{\r\n");
      out.write("\tpadding-left: 10px; \r\n");
      out.write("\tmargin-top: -10px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#new_reply_content{\r\n");
      out.write("\twidth:330px; \r\n");
      out.write("\tborder-radius:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnInsert{\r\n");
      out.write("\tpadding-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**/\r\n");
      out.write("\r\n");
      out.write(".maintext { \r\n");
      out.write("\tpadding-left: 60px; \r\n");
      out.write("\tpadding-right: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".profile {\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("\tobject-position: top;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".w_nickname {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contour {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tposition: static;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".oneanswer {\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".re_picker_img {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tpadding-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".re_picker_nick {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tpadding-right: 20px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".re_content {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".re_write_date {\r\n");
      out.write("\tcolor: #999999;\r\n");
      out.write("\tpadding-left: 55px;\r\n");
      out.write("\tmargin-top: -5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"all_content\">\r\n");
      out.write("\t\t<!--이미지부분-->\r\n");
      out.write("\t\t<div id=\"img_section\">\r\n");
      out.write("\t\t\t<ul class=\"bxslider\">\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--내용부분-->\r\n");
      out.write("\t\t<div id=\"sns_section\">\r\n");
      out.write("\t\t\t<!-- 상단 작성자 정보  -->\r\n");
      out.write("\t\t\t<div id=\"picker_section\">\r\n");
      out.write("\t\t\t\t<div id=\"picker_info1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"w_picker_img1\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"w_picker_nick1\" align=\"left\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr class=\"contour\">\r\n");
      out.write("\t\t\t<!-- 스크롤바 지원 부분 -->\r\n");
      out.write("\t\t\t<div id=\"scroll_section\">\r\n");
      out.write("\t\t\t\t<!-- sns 본문 부분 -->\r\n");
      out.write("\t\t\t\t<div id=\"content_info\">\r\n");
      out.write("\t\t\t\t\t<div id=\"sns_content\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 본문 작성자 정보 -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"picker_info2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"w_picker_img2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"w_picker_nick2\" align=\"left\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 본문 내용 -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"textcontent\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"write_content\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"write_date\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 답글 부분 -->\r\n");
      out.write("\t\t\t\t<div id=\"reply_section\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr class=\"contour\">\r\n");
      out.write("\t\t\t<!--하단고정부분-->\r\n");
      out.write("\t\t\t<div id=\"bottom_section\">\r\n");
      out.write("\t\t\t\t<div id=\"icons\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"new_reply_section\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"new_reply_content\" name=\"new_reply_content\">&nbsp;\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm mr-1 mb-2\" id=\"btnInsert\" name=\"btnInsert\">작성</button> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" id=\"sns_no\" name=\"sns_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sns_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t<!-- 로그인한 계정 정보 (고객이 아닌 경우 cust_no =0 / 사업자가 아닌경우 provider_no =0) -->\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/plugins/plugins.js\"></script>\r\n");
      out.write("\t<script src=\"js/assan.custom.js\"></script>\r\n");
      out.write("\t<script src=\"admin-dashboardUi/js/appUi-custom.js\"></script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t<!--페이지 뽑아오기-->\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar sns_no = $(\"#sns_no\").val();\r\n");
      out.write("\t\tvar login_cust_no = $(\"#login_cust_no\").val();\r\n");
      out.write("\t\tvar login_pro_no = $(\"#login_pro_no\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cust_no;\r\n");
      out.write("\t\tvar provider_no;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cust_img; \r\n");
      out.write("\t\tvar cust_nick;\r\n");
      out.write("\t\tvar pro_img;\r\n");
      out.write("\t\tvar pro_nick;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cu;\r\n");
      out.write("\t\tvar p;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar count_like;\r\n");
      out.write("\t\tvar result;\r\n");
      out.write("\t\tvar isClicked; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*SNS 가져오기*/\t\r\n");
      out.write("\t\tfunction getSNS() {\r\n");
      out.write("\t\t\t$(\"#w_picker_nick1\").empty();\r\n");
      out.write("\t\t\t$(\"#w_picker_img1\").empty();\r\n");
      out.write("\t\t\t$(\"#w_picker_nick2\").empty();\r\n");
      out.write("\t\t\t$(\"#w_picker_img2\").empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#write_content\").empty();\r\n");
      out.write("\t\t\t$(\"#write_date\").empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getSNS.do\",\r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar arr = eval(\"(\" + data + \")\");\t\t\t\r\n");
      out.write("\t\t\t\t\tcust_no = arr.cust_no;\r\n");
      out.write("\t\t\t\t\tprovider_no = arr.provider_no;\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar a;\r\n");
      out.write("\t\t\t\t\tvar h4;\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar font;\r\n");
      out.write("\t\t\t\t\tvar img; \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/*작성자가 사업주일때*/\r\n");
      out.write("\t\t\t\t\tif(cust_no == 0) {\r\n");
      out.write("\t\t\t\t\t\tgetProvInfo(provider_no);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ta = $(\"<a></a>\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(a).click(function() {\r\n");
      out.write("\t\t\t\t\t\t\tparent.location.href = \"snsMyPageView.do?cust_no=-1&provider_no=\" + provider_no;\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\th4 = $(\"<h4 class='w_nickname'></h4>\").html(pro_nick);\r\n");
      out.write("\t\t\t\t\t\tfont = $(\"<font class='w_nickname'></font>\").html(pro_nick);\r\n");
      out.write("\t\t\t\t\t\timg1 = $(\"<img class='profile'/>\").attr({\"src\" : \"prov_img/\" + pro_img}); \r\n");
      out.write("\t\t\t\t\t\timg2 = $(\"<img class='profile'/>\").attr({\"src\" : \"prov_img/\" + pro_img}); \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(a).append(h4);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_nick1\").append(a)\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_nick2\").append(font);\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_img1\").append(img1);\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_img2\").append(img2);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/*작성자가 일반 고객일때*/\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tgetCustInfo(cust_no);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ta = $(\"<a></a>\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(a).click(function() {\r\n");
      out.write("\t\t\t\t\t\t\tparent.location.href = \"snsMyPageView.do?cust_no=\"+cust_no+\"&provider_no=-1\"\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\th4 = $(\"<h4 class='w_nickname'></h4>\").html(cust_nick);\r\n");
      out.write("\t\t\t\t\t\tfont = $(\"<font class='w_nickname'></font>\").html(cust_nick);\r\n");
      out.write("\t\t\t\t\t\timg1 = $(\"<img class='profile'/>\").attr({\"src\" : \"cust_img/\" + cust_img}); \r\n");
      out.write("\t\t\t\t\t\timg2 = $(\"<img class='profile'/>\").attr({\"src\" : \"cust_img/\" + cust_img}); \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(a).append(h4);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_nick1\").append(a)\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_nick2\").append(font);\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_img1\").append(img1);\r\n");
      out.write("\t\t\t\t\t\t$(\"#w_picker_img2\").append(img2);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar p = $(\"<p class='maintext'></p>\").html(arr.sns_content);\r\n");
      out.write("\t\t\t\t\t$(\"#write_content\").append(p);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar strong2 = $(\"<strong></strong>\").html(arr.sns_write_date);\r\n");
      out.write("\t\t\t\t\t$(\"#write_date\").append(strong2);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*sns 태그 가져오기*/\r\n");
      out.write("\t\tfunction getSNSTag(){\r\n");
      out.write("\t\t\t$(\"#write_content\").empty();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getSNSTag.do\",\r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar arr = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\tvar p = $(\"<p class='maintext'></p>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.each(arr, function(idx, st) {\t\t\r\n");
      out.write("\t\t\t\t\t\tvar a = $(\"<a></a>\").html(\"#\"+st.tag_name).attr({\"href\" : \"/listAllSns.do?keyword=\" + st.tag_name});; \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(idx == (arr.length-1) ){\r\n");
      out.write("\t\t\t\t\t\t\t$(p).append(a);\r\n");
      out.write("\t\t\t\t\t\t} else {\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(p).append(a, \", \");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#write_content\").append(\"<br>\",p);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*박스 슬라이더 설정*/\r\n");
      out.write("\t\tfunction setImg () {\r\n");
      out.write("\t\t\t$('.bxslider').bxSlider({\r\n");
      out.write("\t\t\t\tspeed : 1500,\r\n");
      out.write("\t\t\t\tpause : 5000,\r\n");
      out.write("\t\t\t\tmode : 'horizontal',\r\n");
      out.write("\t\t\t\tautoControls : false,\r\n");
      out.write("\t\t\t\tadaptiveWidth : true,\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*이미지 가져오기*/\r\n");
      out.write("\t\tfunction getSNSImg(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getSNSImg.do\",\r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no},\r\n");
      out.write("\t\t\t\tsuccess : function(data) { \r\n");
      out.write("\t\t\t\t\tvar arr = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\t$.each(arr, function(idx, si) {\r\n");
      out.write("\t\t\t\t\t\tvar li = $(\"<li></li>\")\r\n");
      out.write("\t\t\t\t\t\tvar img = $(\"<img width='100%' height='440px'/>\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.attr({\"src\" : \"images/img_sns/\" + si.sns_img_name});\r\n");
      out.write("\t\t\t\t\t\t$(li).append(img);\r\n");
      out.write("\t\t\t\t\t\t$(\".bxslider\").append(li);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsetImg();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*답글 가져오기*/\r\n");
      out.write("\t\tfunction getSNSReply(){\r\n");
      out.write("\t\t\t$(\"#reply_section\").empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getSNSReply.do\", \r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar arr = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.each(arr, function(idx, sr) {\t\t\r\n");
      out.write("\t\t\t\t\t\tvar re_cust_no=0;\r\n");
      out.write("\t\t\t\t\t\tvar re_provider_no=0;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tre_cust_no = sr.cust_no;\r\n");
      out.write("\t\t\t\t\t\tre_provider_no = sr.provider_no;\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar re_cust_img; \r\n");
      out.write("\t\t\t\t\t\tvar re_cust_nick;\r\n");
      out.write("\t\t\t\t\t\tvar re_pro_img;\r\n");
      out.write("\t\t\t\t\t\tvar re_pro_nick;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar div1= $(\"<div class='oneanswer'></div>\");\r\n");
      out.write("\t\t\t\t\t\tvar div2 = $(\"<div class='re_picker_img'></div>\");\r\n");
      out.write("\t\t\t\t\t\tvar div3 = $(\"<div class='re_picker_nick'></div>\");\r\n");
      out.write("\t\t\t\t\t\tvar div4 = $(\"<div class='re_content'></div>\");\t\r\n");
      out.write("\t\t\t\t\t\tvar div5 = $(\"<div class='re_write_date'></div>\");\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar img; \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar font1;\r\n");
      out.write("\t\t\t\t\t\tvar font2;\r\n");
      out.write("\t\t\t\t\t\tvar strong;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar a;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t/*댓글 작성자가 사업주일때*/\r\n");
      out.write("\t\t\t\t\t\tif(re_cust_no == 0) {\r\n");
      out.write("\t\t\t\t\t\t\tgetReProvInfo (re_provider_no);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tre_pro_nick = p.pro_nick;\r\n");
      out.write("\t\t\t\t\t\t\tre_pro_img = p.pro_img;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\ta = $(\"<a style='text-decoration:none;color:#000000;'></a>\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(a).click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tparent.location.href = \"snsMyPageView.do?cust_no=-1&provider_no=\" + re_provider_no;\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\timg = $(\"<img class='profile'/>\").attr({\"src\":\"prov_img/\"+re_pro_img});\r\n");
      out.write("\t\t\t\t\t\t\tfont1 = $(\"<font class='w_nickname'></font>\").html(re_pro_nick);\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t/*댓글 작성자가 일반 고객일때*/\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tgetReCustInfo (re_cust_no);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tre_cust_nick = cu.cust_nick;\r\n");
      out.write("\t\t\t\t\t\t\tre_cust_img = cu.cust_img;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\ta = $(\"<a style='text-decoration:none;color:#000000;'></a>\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(a).click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tparent.location.href = \"snsMyPageView.do?cust_no=\"+re_cust_no+\"&provider_no=-1\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\timg = $(\"<img class='profile'/>\").attr({\"src\":\"cust_img/\"+re_cust_img});\r\n");
      out.write("\t\t\t\t\t\t\tfont1 = $(\"<font class='w_nickname'></font>\").html(re_cust_nick);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfont2 = $(\"<font></font>\").html(sr.reply_content);\r\n");
      out.write("\t\t\t\t\t\tstrong = $(\"<strong><strong>\").html(sr.reply_write_date);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(a).append(font1);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(div2).append(img);\r\n");
      out.write("\t\t\t\t\t\t$(div3).append(a);\r\n");
      out.write("\t\t\t\t\t\t$(div4).append(font2);\r\n");
      out.write("\t\t\t\t\t\t$(div5).append(strong);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(div1).append(div2,div3,div4,div5);\r\n");
      out.write("\t\t\t\t\t\t$(\"#reply_section\").append(div1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*좋아요를 눌렀는지 확인하는 함수*/\r\n");
      out.write("\t\tfunction getIsClicked(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getIsClicked.do\", \r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no, \"cust_no\":login_cust_no, \"provider_no\":login_pro_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tisClicked = data;\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*꽉찬하트로 변경하는 함수*/\r\n");
      out.write("\t\tfunction fullHeart (){\r\n");
      out.write("\t\t\t$(\"#heart\").removeClass(\"fa fa-heart-o fa-2x\");\r\n");
      out.write("\t\t\t$(\"#heart\").addClass(\"fa fa-heart fa-2x\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*빈 하트로 변경하는 함수*/\r\n");
      out.write("\t\tfunction hollowHeart (){\r\n");
      out.write("\t\t\t$(\"#heart\").removeClass(\"fa fa-heart fa-2x\");\r\n");
      out.write("\t\t\t$(\"#heart\").addClass(\"fa fa-heart-o fa-2x\");\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*경우에 따라 하트를 변경하는 함수 */\r\n");
      out.write("\t\tfunction setHeart(){\r\n");
      out.write("\t\t\t/*좋아요를 눌렀을 경우*/\r\n");
      out.write("\t\t\tif(isClicked >0) {\t\r\n");
      out.write("\t\t\t\tsetSNSLike();\r\n");
      out.write("\t\t\t\tfullHeart();\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*좋아요를 누르지 않았을 경우*/\r\n");
      out.write("\t\t\t} else {\t\t\r\n");
      out.write("\t\t\t\tsetSNSLike();\r\n");
      out.write("\t\t\t\thollowHeart();\t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*좋아요를 추가하는 함수*/\r\n");
      out.write("\t\tfunction insertSNSLike(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"insertSNSLike.do\",\r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no, \"cust_no\":login_cust_no, \"provider_no\":login_pro_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tfullHeart ();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*좋아요를 취소하는 함수 */\r\n");
      out.write("\t\tfunction deleteSNSLike (){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"deleteSNSLike.do\",\r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no, \"cust_no\":login_cust_no, \"provider_no\":login_pro_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\thollowHeart ();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*좋아요 수를 가져오는 함수   */\r\n");
      out.write("\t\tfunction getSNSLike (){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getSNSLike.do\", \r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tcount_like = data;\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*좋아요 부분을 화면에 설정하는함수   */\r\n");
      out.write("\t\tfunction setSNSLike(){\r\n");
      out.write("\t\t\t$(\"#icons\").empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetSNSLike();\t\t\r\n");
      out.write("\t\t\tvar icon = $(\"<i id='heart'class='fa fa-heart-o fa-2x' aria-hidden='true'></i>\");\t\r\n");
      out.write("\t\t\tvar btn = $(\"<button id='btnLike'></button>\").html(icon);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar font = $(\"<font id='howmanylikes'></font>\").html(\"&nbsp;&nbsp;\"+ count_like+\"명이 좋아합니다.\");\r\n");
      out.write("\t\t\t$(\"#icons\").append(btn,font);\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#btnLike\").click(function(){\t\r\n");
      out.write("\t\t\t\tif(isClicked >0) {\t\r\n");
      out.write("\t\t\t\t\tdeleteSNSLike();\r\n");
      out.write("\t\t\t\t\tgetIsClicked();\r\n");
      out.write("\t\t\t\t\tsetSNSLike();\r\n");
      out.write("\t\t\t\t\tsetHeart();\r\n");
      out.write("\t\t\t\t} else {\t\t\r\n");
      out.write("\t\t\t\t\tinsertSNSLike();\r\n");
      out.write("\t\t\t\t\tgetIsClicked();\r\n");
      out.write("\t\t\t\t\tsetSNSLike();\r\n");
      out.write("\t\t\t\t\tsetHeart();\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isClicked >0) {\r\n");
      out.write("\t\t\t\t$(\"#btnLike\").hover(function(){\r\n");
      out.write("\t\t\t\t\thollowHeart();\r\n");
      out.write("\t\t\t\t},function(){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfullHeart();\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#btnLike\").hover(function(){\r\n");
      out.write("\t\t\t\t\tfullHeart();\r\n");
      out.write("\t\t\t\t},function(){\t\t\r\n");
      out.write("\t\t\t\t\thollowHeart();\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t/*고객 정보 가져오는 함수  */\t\t\r\n");
      out.write("\t\tfunction getCustInfo (cust_no){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getCustInfo.do\",\r\n");
      out.write("\t\t\t\tdata: {\"cust_no\":cust_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar arr = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\tcust_nick = arr.cust_nick;\r\n");
      out.write("\t\t\t\t\tcust_img = arr.cust_img;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t/*사업자 정보 가져오는 함수  */\r\n");
      out.write("\t\tfunction getProvInfo (provider_no){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getProvInfo.do\", \r\n");
      out.write("\t\t\t\tdata: {\"provider_no\":provider_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar arr = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\tpro_nick = arr.pro_nick;\r\n");
      out.write("\t\t\t\t\tpro_img = arr.pro_img;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t/*댓글 고객 정보 가져오는 함수  */\t\t\r\n");
      out.write("\t\tfunction getReCustInfo (re_cust_no){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getCustInfo.do\",\r\n");
      out.write("\t\t\t\tdata: {\"cust_no\":re_cust_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tcu = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\treturn cu;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t/*댓글 사업자 정보 가져오는 함수  */\r\n");
      out.write("\t\tfunction getReProvInfo (re_provider_no){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"getProvInfo.do\", \r\n");
      out.write("\t\t\t\tdata: {\"provider_no\":re_provider_no}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tp = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\treturn p;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/** 자동으로 실행되는 부분 **/\r\n");
      out.write("\tgetSNS();\t\r\n");
      out.write("\tgetSNSTag();\r\n");
      out.write("\tgetSNSImg();\r\n");
      out.write("\tgetSNSReply();\r\n");
      out.write("\t\t\r\n");
      out.write("\tgetIsClicked(); \t\r\n");
      out.write("\tsetSNSLike();\r\n");
      out.write("\tsetHeart();\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnInsert\").click(function(){\t\t\t\r\n");
      out.write("\t\tvar reply_content = $(\"#new_reply_content\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tif(reply_content != null && reply_content != \"\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"insertSNSReply.do\", \r\n");
      out.write("\t\t\t\tdata: {\"sns_no\":sns_no, \"cust_no\":login_cust_no,\r\n");
      out.write("\t\t\t\t\t\t\"provider_no\":login_pro_no, \"reply_content\":reply_content}, async:false,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tresult = data;\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result > 0) {\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$('#new_reply_content').val('');\r\n");
      out.write("\t\t\t\t\t\tgetSNSReply();\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('#new_reply_content').val('');\r\n");
      out.write("\t\t\t\t\t\tgetSNSReply();\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"내용을 입력하세요.\");\r\n");
      out.write("\t\t}});\t\r\n");
      out.write("\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/detailSNS.jsp(302,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.role eq 'customer' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<input type=\"hidden\" id=\"login_cust_no\" name=\"login_cust_no\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t<input type=\"hidden\" id=\"login_pro_no\" name=\"login_pro_no\" value=\"0\">\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/detailSNS.jsp(306,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.role eq 'provider'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<input type=\"hidden\" id=\"login_cust_no\" name=\"login_cust_no\" value=\"0\">\r\n");
          out.write("\t\t<input type=\"hidden\" id=\"login_pro_no\" name=\"login_pro_no\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
