/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-11-20 05:51:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class intro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/stdLast/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/std_1st/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1570874896139L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <!-- Required meta tags -->\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("        <title>STUDER-PICK</title>    \r\n");
      out.write("        <!-- Plugins CSS -->\r\n");
      out.write("        <link href=\"css/plugins/plugins.css\" rel=\"stylesheet\">\r\n");
      out.write("        <!-- REVOLUTION STYLE SHEETS -->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"revolution/css/settings.css\">\r\n");
      out.write("        <!-- REVOLUTION LAYERS STYLES -->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"revolution/css/layers.css\">\r\n");
      out.write("        <!-- REVOLUTION NAVIGATION STYLES -->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"revolution/css/navigation.css\">\r\n");
      out.write("        <!-- load css for cubeportfolio -->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"cubeportfolio/css/cubeportfolio.min.css\">     \r\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("           <link rel=\"stylesheet\" href=\"assets/dist/css/style.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"preloader\">\r\n");
      out.write("            <div id=\"preloader-inner\"></div>\r\n");
      out.write("        </div><!--/preloader-->\r\n");
      out.write("\r\n");
      out.write("        <!-- Site Overlay -->\r\n");
      out.write("        <div class=\"site-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light navbar-transparent bg-faded nav-sticky\">\r\n");
      out.write("            <div class=\"search-inline\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Type and hit enter...\">\r\n");
      out.write("                    <button type=\"submit\"><i class=\"ti-search\"></i></button>\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"search-close\"><i class=\"ti-close\"></i></a>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div><!--/search form-->\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" \r\n");
      out.write("                data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" \r\n");
      out.write("                aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" \r\n");
      out.write("                aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.do\">\r\n");
      out.write("                    <img class='logo logo-dark' style=\"top:-25px;\" src=\"images/logo.png\" alt=\"\">\r\n");
      out.write("                    <img class='logo logo-light hidden-md-down' style=\"top:-20px;\" src=\"images/logo.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div  id=\"navbarNavDropdown\" class=\"navbar-collapse collapse\">\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                     <!--    <li class=\"nav-item dropdown active\"> -->\r\n");
      out.write("                     \r\n");
      out.write("                    \t <li class=\"nav-item dropdown dropdown-full-width\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"intro\">스투더픽 소개</a>\r\n");
      out.write("                           \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown dropdown-full-width\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"cafeList1.do\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                스터디카페\r\n");
      out.write("                            </a>\r\n");
      out.write("                   \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown dropdown-full-width\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"listStd.do\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                스투더  \r\n");
      out.write("                            </a>\r\n");
      out.write("                       \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"diningSch\">맛집찾기</a>\r\n");
      out.write("                      \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                     \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                         <a class=\"nav-link  dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"#\">고객지원</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\" style=\"background-color: #212121!important\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a tabindex=\"-1\" href=\"listNotice.do\" class=\"dropdown-item\">공지사항</a>\r\n");
      out.write("                                   \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a tabindex=\"-1\" href=\"listQa.do\" class=\"dropdown-item\">Q&A</a>\r\n");
      out.write("                                   \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a tabindex=\"-1\" href=\"listEvt.do\t\" class=\"dropdown-item\">프로모션</a>\r\n");
      out.write("                                    \r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    <ul class=\"nav flex-row order-lg-2 ml-auto nav-icons\"  style=\"margin-left: 50px!important;\" >\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"navbar-right-elements\" style=\"margin: 30px\">\r\n");
      out.write("               \r\n");
      out.write("                </div><!--right nav icons-->\r\n");
      out.write("            </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t\t<!-- 상단 메뉴바? 이미지 -->\r\n");
      out.write("        <div class=\"page-titles-img title-space-lg bg-parallax parallax-overlay mb70\" \r\n");
      out.write("        data-jarallax='{\"speed\": 0.2}' \r\n");
      out.write("        style='background-image: url(\"images/bg1.jpg\")'>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\" col-md-8 ml-auto mr-auto\">\r\n");
      out.write("                        <h1 class='text-uppercase'>스투더픽 </h1>\r\n");
      out.write("\r\n");
      out.write("                        <!--                                    <a href='https://www.youtube.com/watch?v=cctFcl5EFYk' class='modal-video btn btn-white-outline btn-lg btn-rounded'>Watch our film</a>\r\n");
      out.write("                        -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--page title end-->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- ###################################################################### -->\r\n");
      out.write("        <!-- 요기에 넣어!!!!!-->\r\n");
      out.write("        <br><br>\r\n");
      out.write("                <div class='container no-padding mb70'>\r\n");
      out.write("            <div class='row no-margin mb70 align-items-center'>\r\n");
      out.write("                <div class='col-md-4 mb30'>\r\n");
      out.write("                    <div class=\"media pos-relative\">\r\n");
      out.write("                        <div class=\"d-flex mr-3\">\r\n");
      out.write("                            <i class=\"icon-chat fa-2x\"></i>  \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"media-body \">\r\n");
      out.write("                            <h4 class=\"mt-0 mb10  text-uppercase\">최적의 학습 도우미</h4>\r\n");
      out.write("                            \t기존 예약시스템과 차별화를 통해 학생에게는 최적의 학습 목표를, 취업 준비생에게는 성공적인 취업을 달성할 수 있도록 도움을 드립니다\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class='col-md-4 mb30'>\r\n");
      out.write("                    <div class=\"media pos-relative\">\r\n");
      out.write("                        <div class=\"d-flex mr-3\">\r\n");
      out.write("                            <i class=\"icon-trophy fa-2x\"></i>  \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                            <h4 class=\"mt-0 mb10 text-uppercase\">더 넓은 공간을 더 저렴하게 예약하세요</h4>\r\n");
      out.write("                            \t다양한 스터디 카페를 한눈에 꼼꼼하게 비교해 보고, 이벤트 프로모션을 통해 더 넓은 공간을 더 저렴하게 예약하세요\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class='col-md-4 mb30'>\r\n");
      out.write("                    <div class=\"media pos-relative\">\r\n");
      out.write("                        <div class=\"d-flex mr-3\">\r\n");
      out.write("                            <i class=\"icon-global fa-2x\"></i>  \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"media-body \">\r\n");
      out.write("                            <h4 class=\"mt-0 mb10  text-uppercase\">온라인 시스템</h4>\r\n");
      out.write("                           \t\t 대한민국은 지금 스터디카페가 대세! <br>\r\n");
      out.write("                           \t\t 24시간 언제든지 원하는 시간에 자유롭게 예약할 수 있는 시스템!\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class='container mb40'>\r\n");
      out.write("            <div class='row'>\r\n");
      out.write("                <div class='col-lg-10 ml-auto mr-auto'>\r\n");
      out.write("                    <div class=\"title-heading1 mb30\">\r\n");
      out.write("                        <br><br><br><br>\r\n");
      out.write("                        <h3>Meet the team</h3>                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class='lead tritary-font mb50 text-center'>\r\n");
      out.write("            \t최근에 많이 생겨난 스터디 카페. 여러 스터디 카페를 이용하면서 아쉬운 점이 많았습니다. 왜 스터디카페는 한번에 여러 카페를 비교해 보고 예약하는 시스템이 없는 걸까?\r\n");
      out.write("            \t항상 카페마다 전화를 해서 빈자리를 확인하고 직접 가서 결제를 해야만 하는 걸까? 온라인에서 한눈에 비교하고 예약하고 결제까지 한다면, 더 넓고 좋은 공간을 더 저렴하게\r\n");
      out.write("            \t이용할 수 있지 않을까? 이러한 아쉬움을 마음에 담아 스투더픽을 런칭하게 되었습니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class='row'>\r\n");
      out.write("                <div class='col-lg-4 col-md-6 mb30'>\r\n");
      out.write("                    <div class='team-card'>\r\n");
      out.write("                        <img src='images/hb.jpg' alt='' class='img-fluid'>\r\n");
      out.write("                        <div class='team-overlay align-items-center'>\r\n");
      out.write("                            <div class='team-detail'>\r\n");
      out.write("                                <h4>HANBYEOL KO</h4>\r\n");
      out.write("                                <span>HANBYEOL@naver.com</span>\r\n");
      out.write("                                <div class='seprator-overlay'></div>\r\n");
      out.write("                                <ul class='list-inline'>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-facebook'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-twitter'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'> <i class='fa fa-youtube'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-instagram'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--/col-->\r\n");
      out.write("                <div class='col-lg-4 col-md-6 mb30'>\r\n");
      out.write("                    <div class='team-card'>\r\n");
      out.write("                        <img src='images/12345.jpg' alt='' class='img-fluid'>\r\n");
      out.write("                        <div class='team-overlay align-items-center'>\r\n");
      out.write("                            <div class='team-detail'>\r\n");
      out.write("                                <h4>seonkyum Kim</h4>\r\n");
      out.write("                                <span>ycb2@hanmail.net</span>\r\n");
      out.write("                                <div class='seprator-overlay'></div>\r\n");
      out.write("                                <ul class='list-inline'>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-facebook'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-twitter'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'> <i class='fa fa-youtube'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-instagram'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--/col-->\r\n");
      out.write("                <div class='col-lg-4 col-md-6 mb30'>\r\n");
      out.write("                    <div class='team-card'>\r\n");
      out.write("                        <img src='images/23456.jpg' alt='' class='img-fluid'>\r\n");
      out.write("                        <div class='team-overlay align-items-center'>\r\n");
      out.write("                            <div class='team-detail'>\r\n");
      out.write("                                <h4>Heejin Choi</h4>\r\n");
      out.write("                                <span>Heejin@gamil.com</span>\r\n");
      out.write("                                <div class='seprator-overlay'></div>\r\n");
      out.write("                                <ul class='list-inline'>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-facebook'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-twitter'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'> <i class='fa fa-youtube'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-instagram'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--/col-->\r\n");
      out.write("                <div class='col-lg-4 col-md-6 mb30'>\r\n");
      out.write("                    <div class='team-card'>\r\n");
      out.write("                        <img src='images/34567.jpg' alt='' class='img-fluid'>\r\n");
      out.write("                        <div class='team-overlay align-items-center'>\r\n");
      out.write("                            <div class='team-detail'>\r\n");
      out.write("                                <h4>Soyeun Kim</h4>\r\n");
      out.write("                                <span>kimsoyeun@naver.com</span>\r\n");
      out.write("                                <div class='seprator-overlay'></div>\r\n");
      out.write("                                <ul class='list-inline'>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-facebook'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-twitter'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'> <i class='fa fa-youtube'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-instagram'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--/col-->\r\n");
      out.write("                                <div class='col-lg-4 col-md-6 mb30'>\r\n");
      out.write("                    <div class='team-card'>\r\n");
      out.write("                        <img src='images/45678.jpg' alt='' class='img-fluid'>\r\n");
      out.write("                        <div class='team-overlay align-items-center'>\r\n");
      out.write("                            <div class='team-detail'>\r\n");
      out.write("                                <h4>Seongbin Moon</h4>\r\n");
      out.write("                                <span>moonsb@nate.com</span>\r\n");
      out.write("                                <div class='seprator-overlay'></div>\r\n");
      out.write("                                <ul class='list-inline'>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-facebook'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-twitter'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'> <i class='fa fa-youtube'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-instagram'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--/col-->\r\n");
      out.write("                                <div class='col-lg-4 col-md-6 mb30'>\r\n");
      out.write("                    <div class='team-card'>\r\n");
      out.write("                        <img src='images/56789.jpg' alt='' class='img-fluid'>\r\n");
      out.write("                        <div class='team-overlay align-items-center'>\r\n");
      out.write("                            <div class='team-detail'>\r\n");
      out.write("                                <h4>Seonyeong Park</h4>\r\n");
      out.write("                                <span>Seonyeong@naver.com</span>\r\n");
      out.write("                                <div class='seprator-overlay'></div>\r\n");
      out.write("                                <ul class='list-inline'>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-facebook'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-twitter'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'> <i class='fa fa-youtube'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class='list-inline-item'>\r\n");
      out.write("                                        <a href='#'><i class='fa fa-instagram'></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--/col-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--team-->\r\n");
      out.write("        <div class='container mb50'>\r\n");
      out.write("            <div class=\"title-heading1 mb30\">\r\n");
      out.write("             <br><br><br><br><br>\r\n");
      out.write("                <h3>why choose us</h3>                       \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row special-feature\">\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 margin20\">\r\n");
      out.write("                    <div class=\"s-feature-box text-center\">\r\n");
      out.write("                        <div class=\"mask-top\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-heart-o\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>예약을 쉽고 빠르게</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mask-bottom\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-heart-o\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>예약을 쉽고 빠르게</h4>\r\n");
      out.write("                            <!-- Text -->\r\n");
      out.write("                            <p>여러 스터디 카페를 한눈에 비교하여 선택한 후 쉽고 빠르게 예약과 결제를 할 수 있습니다</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div><!--services col-->\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 margin20\">\r\n");
      out.write("                    <div class=\"s-feature-box text-center\">\r\n");
      out.write("                        <div class=\"mask-top\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-laptop\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>스터디 모임 검색 및 개설</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mask-bottom\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-laptop\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>스터디 모임 검색 및 개설</h4>\r\n");
      out.write("                            <!-- Text -->\r\n");
      out.write("                            <p>관심있는 스터디 모임을 지역별, 종류별로 검색하여 참가 신청할 수 있으며, 직접 모임을 개설할 수도 있습니다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--services col-->\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 margin20\">\r\n");
      out.write("                    <div class=\"s-feature-box text-center\">\r\n");
      out.write("                        <div class=\"mask-top\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-code\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>카페 근처 맛집 추천</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mask-bottom\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-code\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>카페 근처 맛집 추천</h4>\r\n");
      out.write("                            <!-- Text -->\r\n");
      out.write("                            <p>예약한 스터디 카페 근처의 맛집을 자동으로 추천하여, 식당을 검색해야 하는 고민과 수고를 덜어 드립니다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--services col-->\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6 margin20\">\r\n");
      out.write("                    <div class=\"s-feature-box text-center\">\r\n");
      out.write("                        <div class=\"mask-top\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-cogs\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>SNS 연동을 통한 스터디 모임 활성화</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mask-bottom\">\r\n");
      out.write("                            <!-- Icon -->\r\n");
      out.write("                            <i class=\"fa fa-cogs\"></i>\r\n");
      out.write("                            <!-- Title -->\r\n");
      out.write("                            <h4>SNS 연동을 통한 스터디 모임 활성화</h4>\r\n");
      out.write("                            <!-- Text -->\r\n");
      out.write("                            <p>SNS 연동을 통해 스터디원이 함께 스터디 내용과 일상을 공유할 수 있습니다. 더 재미있고 즐겁게 모임에 참가하세요. </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!--services col-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class='bg-faded pt100 pb100'>\r\n");
      out.write("            <div class='container text-center'>\r\n");
      out.write("                <div class='row'>\r\n");
      out.write("                    <div class='col-lg-8 col-md-10 ml-auto mr-auto'>\r\n");
      out.write("                        <h2 class='mb10'>스터디 카페 예약을 쉽고! 빠르게!</h2>\r\n");
      out.write("                        <p class='mb20 lead'>\r\n");
      out.write("                             \t스터디 카페 예약. 더이상 카페 마다 전화해서 빈자리를 확인하고 예약하고\r\n");
      out.write("                             \t내방하여<br> 결제할 필요가 없습니다.빈자리 확인부터 결제까지 빠르게 논스탑으로 이용하세요!\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a target='_blank' href='cafeList1.do' class=\"btn btn-outline-warning mb5 btn-rounded\">스터디카페 확인하러 가기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        <footer class=\"footer footer-dark pt50 pb30\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6  ml-auto mr-auto text-center\">\r\n");
      out.write("                        <ul class=\"social-icons list-inline\">\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-facebook\"></i>Facebook\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-twitter\"></i>twitter\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-instagram\"></i>instagram\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-behance\"></i>Behance\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <h4><i class=\"fa fa-phone\"></i>010-6868-9295</h4>\r\n");
      out.write("                        <h4><i class=\"fa fa-envelope\"></i>msb9876@naver.com</h4>\r\n");
      out.write("                        <p>© Copyright  by Team BoB</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer><!--/footer-->\r\n");
      out.write("        <!--back to top-->\r\n");
      out.write("        <a href=\"#\" class=\"back-to-top hidden-xs-down\" id=\"back-to-top\"><i class=\"ti-angle-up\"></i></a>\r\n");
      out.write("        <!-- jQuery first, then Tether, then Bootstrap JS. -->\r\n");
      out.write("        <script src=\"js/plugins/plugins.js\"></script> \r\n");
      out.write("        <script src=\"js/assan.custom.js\"></script> \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/intro.jsp(80,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginVo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        \t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        \t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/intro.jsp(82,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.role eq 'customer' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t\t\t<a id=\"SNS\" class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"snsMyPageView.do?cust_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&provider_no=-1\" >SNS</a>\r\n");
          out.write("                        \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t\t\t<a id=\"SNS\" class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"snsMyPageView.do?cust_no=-1&provider_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >SNS</a>\t\r\n");
          out.write("                        \t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/intro.jsp(90,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginVo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t<a class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"login\" >SNS</a>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/intro.jsp(117,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginVo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"nav-item dropdown user-dropdown align-items-center\" >\r\n");
          out.write("                                    <a class=\"nav-link\" href=\"#\" id=\"dropdown-user\" role=\"button\"\r\n");
          out.write("                                       data-toggle=\"dropdown\">\r\n");
          out.write("                                <span class=\"user-states states-online\">\r\n");
          out.write("                                    <img src=\"cust_img/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.cust_img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"35\" height=\"35px!important\" alt=\"\" class=\"rounded-circle\">\r\n");
          out.write("                                </span>\r\n");
          out.write("                                        <span class=\"ml-2 h-lg-down dropdown-toggle\">\r\n");
          out.write("                                                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.nick_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                        </span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                    <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdown-user\" style=\"background-color: #212121!important\" >\r\n");
          out.write("                                        <a class=\"dropdown-item\" href=\"profile\"><i class=\"icon-User\"></i>My Profile</a>\r\n");
          out.write("                                        ");
          if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        <!--추가하면 되는 부분  -->\r\n");
          out.write("                                        <a class=\"dropdown-item\" href=\"logout\"><i class=\"icon-Power\"></i>\r\n");
          out.write("                                            Log Out</a>\r\n");
          out.write("\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                </li>\r\n");
          out.write("                                <li class=\"h-lg-up nav-item\">\r\n");
          out.write("                                    <a href=\"#\" class=\" nav-link collapsed\" data-toggle=\"collapse\"\r\n");
          out.write("                                       data-target=\"#navbarToggler\" aria-expanded=\"false\">\r\n");
          out.write("                                        <i class=\"icon-Magnifi-Glass2\"></i>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        \t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        \t");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/intro.jsp(131,41) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.role eq 'customer' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        \t\t <a class=\"dropdown-item\" href=\"custMyPage?cust_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><i class=\"icon-User\"></i>고객 My Page</a>\r\n");
          out.write("                                        \t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        \t\t<a class=\"dropdown-item\" href=\"provMyPageView.do?cust_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><i class=\"icon-User\"></i>사업자 My Page</a>\r\n");
          out.write("                                        \t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                           \t\t<li><a href=\"login\"><font style=\"color: #F4923D\">Join Us</font></a></li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }
}
