/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-11-20 05:49:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listStd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/stdLast/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/std_1st/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1570874896139L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>STUDER-PICK</title>\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"assets/images/fav.ico\"\r\n");
      out.write("\ttype=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"assets/images/fav.ico\" type=\"image/x-icon\">\r\n");
      out.write("<!-- fonts CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/fonts/linearicons/fonts.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"assets/fonts/font-awesome/css/fontawesome-all.min.css\">\r\n");
      out.write("<!-- Custom CSS File -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/dist/css/style.css\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Plugins CSS -->\r\n");
      out.write("<link href=\"css/plugins/plugins.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- REVOLUTION STYLE SHEETS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"revolution/css/settings.css\">\r\n");
      out.write("<!-- REVOLUTION LAYERS STYLES -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"revolution/css/layers.css\">\r\n");
      out.write("<!-- REVOLUTION NAVIGATION STYLES -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"revolution/css/navigation.css\">\r\n");
      out.write("<!-- load css for cubeportfolio -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"cubeportfolio/css/cubeportfolio.min.css\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".select_sido {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 100px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-bottom: 70px;\r\n");
      out.write("\tpadding-bottom: 70px;\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".font_searchStd {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 445px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main_container {\r\n");
      out.write("\tflex: 100%;\r\n");
      out.write("\tmax-width: 80%;\r\n");
      out.write("\tmargin-left: 15%; /*오른쪽 화면 여백이 너무 많을 경우 숫자를 늘리면 됩니다.*/\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"preloader\">\r\n");
      out.write("\t\t<div id=\"preloader-inner\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--/preloader-->\r\n");
      out.write("\t<!-- Site Overlay -->\r\n");
      out.write("\t<div class=\"site-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light navbar-transparent bg-faded nav-sticky\">\r\n");
      out.write("            <div class=\"search-inline\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Type and hit enter...\">\r\n");
      out.write("                    <button type=\"submit\"><i class=\"ti-search\"></i></button>\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"search-close\"><i class=\"ti-close\"></i></a>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div><!--/search form-->\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" \r\n");
      out.write("                data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" \r\n");
      out.write("                aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" \r\n");
      out.write("                aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.do\">\r\n");
      out.write("                    <img class='logo logo-dark' style=\"top:-25px;\" src=\"images/logo.png\" alt=\"\">\r\n");
      out.write("                    <img class='logo logo-light hidden-md-down' style=\"top:-20px;\" src=\"images/logo.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div  id=\"navbarNavDropdown\" class=\"navbar-collapse collapse\">\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                     <!--    <li class=\"nav-item dropdown active\"> -->\r\n");
      out.write("                     \r\n");
      out.write("                    \t <li class=\"nav-item dropdown dropdown-full-width\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"intro\">스투더픽 소개</a>\r\n");
      out.write("                           \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown dropdown-full-width\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"cafeList1.do\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                스터디카페\r\n");
      out.write("                            </a>\r\n");
      out.write("                   \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown dropdown-full-width\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"listStd.do\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                스투더  \r\n");
      out.write("                            </a>\r\n");
      out.write("                       \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"diningSch\">맛집찾기</a>\r\n");
      out.write("                      \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                     \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                         <a class=\"nav-link  dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"#\">고객지원</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\" style=\"background-color: #212121!important\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a tabindex=\"-1\" href=\"listNotice.do\" class=\"dropdown-item\">공지사항</a>\r\n");
      out.write("                                   \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a tabindex=\"-1\" href=\"listQa.do\" class=\"dropdown-item\">Q&A</a>\r\n");
      out.write("                                   \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a tabindex=\"-1\" href=\"listEvt.do\t\" class=\"dropdown-item\">프로모션</a>\r\n");
      out.write("                                    \r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    <ul class=\"nav flex-row order-lg-2 ml-auto nav-icons\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"navbar-right-elements\" style=\"margin: 30px\">\r\n");
      out.write("               \r\n");
      out.write("                </div><!--right nav icons-->\r\n");
      out.write("            </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 상단 메뉴바? 이미지 -->\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tclass=\"page-titles-img title-space-lg bg-parallax parallax-overlay mb70\"\r\n");
      out.write("\t\tdata-jarallax='{\"speed\": 0.2}'\r\n");
      out.write("\t\tstyle='background-image: url(\"images/std1.jpg\")'>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\" col-md-8 ml-auto mr-auto\">\r\n");
      out.write("\t\t\t\t\t<h1 class='text-uppercase'>스&nbsp;&nbsp;투&nbsp;&nbsp;더</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <a href='https://www.youtube.com/watch?v=cctFcl5EFYk' class='modal-video btn btn-white-outline btn-lg btn-rounded'>Watch our film</a>\r\n");
      out.write("                        -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--page title end-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ###################################################################### -->\r\n");
      out.write("\t<!--Page content -->\r\n");
      out.write("\t<form class=\"form-inline ml-1\">\r\n");
      out.write("\t\t<div class=\"select_sido\">\r\n");
      out.write("\t\t\t<font class=\"font_sido\">지역 </font> <select name=\"sido\" id=\"sido\"\r\n");
      out.write("\t\t\t\tclass=\"form-control border0\"></select> <select name=\"gugun\"\r\n");
      out.write("\t\t\t\tid=\"gugun\" class=\"form-control border0\"></select> <br> <br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"search_std\">\r\n");
      out.write("\t\t\t<font class=\"font_searchStd\"> 스투더 검색 </font> <input id=\"keyword\" name=\"keyword\"\r\n");
      out.write("\t\t\t\tclass=\"form-control border0\" type=\"search\" placeholder=\"Search...\"\r\n");
      out.write("\t\t\t\taria-label=\"Search\" width=\"35\"\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; right: 200px; width: 250px\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-warning mb5 btn-rounded\" id=\"btnSearch\" name=\"btnSearch\"\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; right: 100px; text-align: center;\">검색</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" id=\"h_keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"h_sido\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"h_gugun\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gugun}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container pt100 pb70\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-9 mb30 sticky-content\" id=\"main_container\">\r\n");
      out.write("\t\t\t\t<!--본문 시작-->\r\n");
      out.write("\t\t\t\t<div id=\"std_board\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--본문 끝 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"pagination\" id=\"pagination\"\r\n");
      out.write("\t\tstyle=\"align-items: center; align-content: center; margin-left: 45%; margin-right: 45%;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!--Page content -->\r\n");
      out.write(" <footer class=\"footer footer-dark pt50 pb30\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6  ml-auto mr-auto text-center\">\r\n");
      out.write("                        <ul class=\"social-icons list-inline\">\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-facebook\"></i>Facebook\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-twitter\"></i>twitter\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-instagram\"></i>instagram\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-inline-item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-behance\"></i>Behance\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <h4><i class=\"fa fa-phone\"></i>010-6868-9295</h4>\r\n");
      out.write("                        <h4><i class=\"fa fa-envelope\"></i>msb9876@naver.com</h4>\r\n");
      out.write("                        <p>© Copyright  by Team BoB</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer><!--/footer-->\r\n");
      out.write("\r\n");
      out.write("\t<!--back to top-->\r\n");
      out.write("\t<a href=\"#\" class=\"back-to-top hidden-xs-down\" id=\"back-to-top\"><i\r\n");
      out.write("\t\tclass=\"ti-angle-up\"></i></a>\r\n");
      out.write("\t<!-- jQuery first, then Tether, then Bootstrap JS. -->\r\n");
      out.write("\t<script src=\"js/plugins/plugins.js\"></script>\r\n");
      out.write("\t<script src=\"js/assan.custom.js\"></script>\r\n");
      out.write("\t<script src=\"assets/dist/js/plugins.js\"></script>\r\n");
      out.write("\t<script src=\"assets/dist/js/education.custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t<!--시/군/구 콤보박스-->\r\n");
      out.write("\t\t$('document')\r\n");
      out.write("\t\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar area0 = [ \"시/도 선택\", \"서울특별시\", \"인천광역시\", \"대전광역시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"광주광역시\", \"대구광역시\", \"울산광역시\", \"부산광역시\", \"경기도\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"강원도\", \"충청북도\", \"충청남도\", \"전라북도\", \"전라남도\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"경상북도\", \"경상남도\", \"제주도\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area1 = [ \"강남구\", \"강동구\", \"강북구\", \"강서구\", \"관악구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"광진구\", \"구로구\", \"금천구\", \"노원구\", \"도봉구\", \"동대문구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"동작구\", \"마포구\", \"서대문구\", \"서초구\", \"성동구\", \"성북구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"송파구\", \"양천구\", \"영등포구\", \"용산구\", \"은평구\", \"종로구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"중구\", \"중랑구\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area2 = [ \"계양구\", \"남구\", \"남동구\", \"동구\", \"부평구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"서구\", \"연수구\", \"중구\", \"강화군\", \"옹진군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area3 = [ \"대덕구\", \"동구\", \"서구\", \"유성구\", \"중구\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area4 = [ \"광산구\", \"남구\", \"동구\", \"북구\", \"서구\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area5 = [ \"남구\", \"달서구\", \"동구\", \"북구\", \"서구\", \"수성구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"중구\", \"달성군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area6 = [ \"남구\", \"동구\", \"북구\", \"중구\", \"울주군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area7 = [ \"강서구\", \"금정구\", \"남구\", \"동구\", \"동래구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"부산진구\", \"북구\", \"사상구\", \"사하구\", \"서구\", \"수영구\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"연제구\", \"영도구\", \"중구\", \"해운대구\", \"기장군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area8 = [ \"고양시\", \"과천시\", \"광명시\", \"광주시\", \"구리시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"군포시\", \"김포시\", \"남양주시\", \"동두천시\", \"부천시\", \"성남시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"수원시\", \"시흥시\", \"안산시\", \"안성시\", \"안양시\", \"양주시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"오산시\", \"용인시\", \"의왕시\", \"의정부시\", \"이천시\", \"파주시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"평택시\", \"포천시\", \"하남시\", \"화성시\", \"가평군\", \"양평군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"여주군\", \"연천군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area9 = [ \"강릉시\", \"동해시\", \"삼척시\", \"속초시\", \"원주시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"춘천시\", \"태백시\", \"고성군\", \"양구군\", \"양양군\", \"영월군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"인제군\", \"정선군\", \"철원군\", \"평창군\", \"홍천군\", \"화천군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"횡성군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area10 = [ \"제천시\", \"청주시\", \"충주시\", \"괴산군\", \"단양군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"보은군\", \"영동군\", \"옥천군\", \"음성군\", \"증평군\", \"진천군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"청원군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area11 = [ \"계룡시\", \"공주시\", \"논산시\", \"보령시\", \"서산시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"아산시\", \"천안시\", \"금산군\", \"당진군\", \"부여군\", \"서천군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"연기군\", \"예산군\", \"청양군\", \"태안군\", \"홍성군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area12 = [ \"군산시\", \"김제시\", \"남원시\", \"익산시\", \"전주시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"정읍시\", \"고창군\", \"무주군\", \"부안군\", \"순창군\", \"완주군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"임실군\", \"장수군\", \"진안군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area13 = [ \"광양시\", \"나주시\", \"목포시\", \"순천시\", \"여수시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"강진군\", \"고흥군\", \"곡성군\", \"구례군\", \"담양군\", \"무안군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"보성군\", \"신안군\", \"영광군\", \"영암군\", \"완도군\", \"장성군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"장흥군\", \"진도군\", \"함평군\", \"해남군\", \"화순군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area14 = [ \"경산시\", \"경주시\", \"구미시\", \"김천시\", \"문경시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"상주시\", \"안동시\", \"영주시\", \"영천시\", \"포항시\", \"고령군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"군위군\", \"봉화군\", \"성주군\", \"영덕군\", \"영양군\", \"예천군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"울릉군\", \"울진군\", \"의성군\", \"청도군\", \"청송군\", \"칠곡군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area15 = [ \"거제시\", \"김해시\", \"마산시\", \"밀양시\", \"사천시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"양산시\", \"진주시\", \"진해시\", \"창원시\", \"통영시\", \"거창군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"고성군\", \"남해군\", \"산청군\", \"의령군\", \"창녕군\", \"하동군\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"함안군\", \"함양군\", \"합천군\" ];\r\n");
      out.write("\t\t\t\t\t\t\tvar area16 = [ \"서귀포시\", \"제주시\", \"남제주군\", \"북제주군\" ];\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 시/도 선택 박스 초기화\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$(\"select[name^=sido]\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$selsido = $(this);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\teval(area0),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$selsido\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\"<option value='\"+this+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$selsido\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.next()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"<option value=''>구/군 선택</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 시/도 선택시 구/군 설정\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$(\"select[name^=sido]\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar area = \"area\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ $(\"option\", $(this))\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.index(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"option:selected\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(this))); // 선택지역의 구군 Array\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar $gugun = $(this).next(); // 선택영역 군구 객체\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"option\", $gugun).remove(); // 구군 초기화\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (area == \"area0\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$gugun\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\"<option value=''>구/군 선택</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\teval(area),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$gugun\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\"<option value='\"+this+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t<!--스투더 목록-->\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar keyword;\t\t//입력받은 검색어\r\n");
      out.write("\t\t\tvar sido;\t\t\t//선택한 시/도\r\n");
      out.write("\t\t\tvar gugun;\t\t\t//선택한 구/군\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar pageSIZE = 5;\t\t//한 페이지당 보여줄 레코드 수\r\n");
      out.write("\t\t\tvar pageGROUP = 5;\t\t//한 화면에 보여줄 페이지수\r\n");
      out.write("\t\t\tvar totalRecord = 0;\t\t//전체 레코드 수\r\n");
      out.write("\t\t\tvar totalPage = 1; \t\t//전체 페이지 수\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar today = new Date(); //오늘날짜함수 \r\n");
      out.write("\t\t\tvar todate; //오늘날짜(yyyymmdd)를 담을 변수\r\n");
      out.write("\t\t\tvar getdate; //스투더 시작날짜(yyyymmdd)를 담을 변수\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({url:\"getCountStd.do\", \r\n");
      out.write("\t\t\t\tdata:{\"keyword\":keyword,\"sido\":sido, \"gugun\":gugun}, async:false,\r\n");
      out.write("\t\t\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\t\t\ttotalRecord = data;\t\t\t\t\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\ttotalPage = parseInt(totalRecord / pageSIZE);\r\n");
      out.write("\t\t\tif(totalRecord % pageSIZE !=0) {\r\n");
      out.write("\t\t\t\ttotalPage++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar currentPage = 1;\r\n");
      out.write("\t\t\tvar start = (currentPage-1) * pageSIZE +1;\r\n");
      out.write("\t\t\tvar end = currentPage * pageSIZE;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#btnSearch\").click(function(){\r\n");
      out.write("\t\t\t\tkeyword = $(\"#keyword\").val();\r\n");
      out.write("\t\t\t\tsido = $(\"#sido\").val();\r\n");
      out.write("\t\t\t\tgugun = $(\"#gugun\").val();\r\n");
      out.write("\t\t\t\tcurrentPage = 1;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({url:\"getCountStd.do\", \r\n");
      out.write("\t\t\t\t\tdata:{\"keyword\":keyword,\"sido\":sido, \"gugun\":gugun}, async:false,\r\n");
      out.write("\t\t\t\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\t\t\t\ttotalRecord = data;\t\t\t\t\r\n");
      out.write("\t\t\t\t}});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttotalPage = parseInt(totalRecord / pageSIZE);\r\n");
      out.write("\t\t\t\tif(totalRecord % pageSIZE !=0) {\r\n");
      out.write("\t\t\t\t\ttotalPage++;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tgetListStd();\r\n");
      out.write("\t\t\t\tpaging();\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//날짜를 올바른 형식으로 바꿔주는 함수\r\n");
      out.write("\t\t\t Date.prototype.yyyymmdd = function() {\r\n");
      out.write("  \t\t \t\tvar yyyy = this.getFullYear().toString();\r\n");
      out.write("   \t\t\t\tvar mm = (this.getMonth() + 1).toString();\r\n");
      out.write("   \t\t \t\tvar dd = this.getDate().toString();\r\n");
      out.write("   \t\t \t\treturn  yyyy + \"-\" + (mm[1] ? mm : \"0\" + mm[0]) + \"-\" + (dd[1] ? dd : \"0\" + dd[0]);\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//String을  date 타입으로 바꿔주는 함수\r\n");
      out.write("\t\t\t function parse(str) {\r\n");
      out.write("\t\t\t\t var y = str.substr(0,4),\r\n");
      out.write("                m = str.substr(5,2),\r\n");
      out.write("                d = str.substr(8,2);\r\n");
      out.write("\t\t\t\t    return new Date(y,m,d);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//목록 가져오는 함수 \r\n");
      out.write("\t\t\tfunction getListStd() {\r\n");
      out.write("\t\t\t\t$(\"#std_board\").empty();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tkeyword = $(\"#keyword\").val();\r\n");
      out.write("\t\t\t\tsido = $(\"#sido\").val();\r\n");
      out.write("\t\t\t\tgugun = $(\"#gugun\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({url : \"getListStd.do\",\r\n");
      out.write("\t\t\t\t\t\tdata : {\"keyword\":keyword, \"sido\":sido, \"gugun\":gugun,\"start\":start,\"end\":end  },\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tvar arr = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\t\t\t//검색결과가 없을 시 문구 표기 \r\n");
      out.write("\t\t\t\t\t\t\tif(data == \"[]\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar h2 = $(\"<h2></h2>\").html(\"검색 결과가 없습니다.\");\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#std_board\").append(h2);\t\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.each(arr,function(idx, std) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttodate = parse(today.yyyymmdd());\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgetdate = parse(std.std_close);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div1 = $(\"<div class='course-list-item mb30'></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div2 = $(\"<div class='row align-items-center'></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div3_1 = $(\"<div class='col-md-3 col-sm-12 py-2'></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar a_img = $(\"<a></a>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar img;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (std.std_image != null) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\timg = $(\"<img class='img-fluid'>\").attr(\"src\",\"images/std_img/upload/\"+std.std_image);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\timg = $(\"<img class='img-fluid'>\").attr(\"src\",\"images/std_img/upload/std_default.PNG\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div3_2 = $(\"<div class='col-md-6 col-sm-12 py-3'></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar a_title;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(todate<=getdate) {\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ta_title = $(\"<a></a>\").attr({\"href\" : \"detailStd.do?std_no=\"+ std.std_no +\"&isClosed=-1\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ta_title = $(\"<a></a>\").attr({\"href\" : \"detailStd.do?std_no=\"+ std.std_no +\"&isClosed=1\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar h5 = $(\"<h5></h5>\").html(std.std_name);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar p_intro = $(\"<p class='mb-0'></p>\").html(std.std_intro);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar br = $(\"<br>\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar ul = $(\"<ul class='list-inline'></ul>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar li1 = $(\"<li class='list-inline-item mr-3'></li>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div4_1 = $(\"<div></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar i1 = $(\"<i class='fa fa-calendar mr-2'></i>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar p1 = $(\"<p>기간</p>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar a1 = $(\"<a href='#'></a>\").html(std.std_start+ \" ~ \"+ std.std_end);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar li2 = $(\"<li class='list-inline-item mr-3'></li>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div4_2 = $(\"<div></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar i2 = $(\"<i class='fa fa-calendar-check-o mr-2'></i>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar p2 = $(\"<p>마감일</p>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar a2 = $(\"<a href='#'></a>\").html(std.std_close);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar li3 = $(\"<li class='list-inline-item mr-3'></li>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div4_3 = $(\"<div></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar i3 = $(\"<i class='fa fa-map-marker mr-2'></i>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar p3 = $(\"<p>장소</p>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar a3 = $(\"<a href='#'></a>\").html(std.std_loc);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar li4 = $(\"<li class='list-inline-item mr-3'></li>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div4_4 = $(\"<div></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar i4 = $(\"<i class='fa fa-user mr-2'></i>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar p4 = $(\"<p>모집현황</p>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar a4;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(std.std_limit > std.picker_count){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ta4 = $(\"<a href='#'></a>\").html(std.std_limit+\"명 중 \"+std.picker_count+\"명 모집\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else if (std.std_limit <= std.picker_count) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ta4 = $(\"<a href='#'></a>\").html(\"모집 완료\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar li5 = $(\"<li class='list-inline-item mr-3'></li>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div4_5 = $(\"<div></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar i5 = $(\"<i class='fa fa-eye mr-2'></i>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar p5 = $(\"<p>조회수</p>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar a5 = $(\"<a href='#'></a>\").html(std.std_hits);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar div3_3 = $(\"<div class='col-md-3 py-2 col-12'></div>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar join;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar std_no = std.std_no\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(todate<=getdate) {\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tjoin = $(\"<a class=' btn btn-outline-warning mb5'></a>\").html(\"참여하기\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.attr({\"href\" : \"detailStd.do?std_no=\"+ std.std_no +\"&isClosed=-1\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(join).click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\turl:\"updateStdHit\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata:{\"std_no\" : std.std_no},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tgetListStd();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tjoin = $(\"<a class=' btn btn-outline-warning mb5'></a>\").html(\"모집종료\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.attr({\"href\" : \"detailStd.do?std_no=\"+ std.std_no +\"&isClosed=1\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(join).click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\turl:\"updateStdHit\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata:{\"std_no\" : std.std_no},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tgetListStd();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(div3_3).append(join);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(li1).append(i1, \"기간 \",a1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(li2).append(i2, \" 마감일 \",a2);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(li3).append(i3, \" 장소 \",a3);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(li4).append(i4, \" 모집현황 \",a4);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(li5).append(i5, \" 조회수 \",a5);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(ul).append(li1, li2, li3,li4, li5);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(a_title).append(h5);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(div3_2).append(a_title,p_intro, br, ul);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(a_img).append(img);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(div3_1).append(a_img);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(div2).append(div3_1,div3_2, div3_3);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(div1).append(div2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#std_board\").append(div1);\r\n");
      out.write("\t\t\t\t\t\t\t\t});\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//페이지 출력 하는 메소드\r\n");
      out.write("\t\t\tfunction paging() {\r\n");
      out.write("\t\t\t\t$(\"#pagination\").empty();\r\n");
      out.write("\t\t\t\t//한 화면에 보여줄 시작페이지, 끝페이지 구하기\r\n");
      out.write("\t\t\t\tvar startPage = parseInt(currentPage/pageGROUP) * pageGROUP + 1;\r\n");
      out.write("\t\t\t\tif(currentPage % 5 == 0) {\r\n");
      out.write("\t\t\t\t\tstartPage = (parseInt(currentPage/pageGROUP)-1) * pageGROUP + 1;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar endPage = startPage + pageGROUP - 1;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(endPage > totalPage) {\r\n");
      out.write("\t\t\t\t\tendPage = totalPage;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(currentPage > pageGROUP) {\r\n");
      out.write("\t\t\t\t\tvar btn_prev = $(\"<a class='page-link'><i class='fa fa-caret-left'></i></a>\");\r\n");
      out.write("\t\t\t\t\t$(\"#pagination\").append(btn_prev);\r\n");
      out.write("\t\t\t\t\t$(btn_prev).click(function() {\r\n");
      out.write("\t\t\t\t\t\tcurrentPage = startPage - 1;\r\n");
      out.write("\t\t\t\t\t\tstart = (currentPage-1) * pageSIZE +1;\r\n");
      out.write("\t\t\t\t\t\tend = currentPage * pageSIZE;\r\n");
      out.write("\t\t\t\t\t\tgetListStd();\r\n");
      out.write("\t\t\t\t\t\tpaging();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\tfor(var i=startPage; i<=endPage; i++) {\r\n");
      out.write("\t\t\t\t\tvar a = $(\"<a class='page-link pg'>\"+i+\"</a>\");\r\n");
      out.write("\t\t\t\t\t$(\"#pagination\").append(a);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\".pg\").click(function() {\r\n");
      out.write("\t\t\t\t\tcurrentPage = $(this).html();\r\n");
      out.write("\t\t\t\t\tstart = (currentPage-1) * pageSIZE +1;\r\n");
      out.write("\t\t\t\t\tend = currentPage * pageSIZE;\r\n");
      out.write("\t\t\t\t\tgetListStd();\r\n");
      out.write("\t\t\t\t\tpaging();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(currentPage < totalPage && endPage+1<=totalPage) {\r\n");
      out.write("\t\t\t\t\tvar btn_next = $(\"<a class='page-link'><i class='fa fa-caret-right'></i></a>\");\r\n");
      out.write("\t\t\t\t\t$(\"#pagination\").append(btn_next);\r\n");
      out.write("\t\t\t\t\t$(btn_next).click(function() {\r\n");
      out.write("\t\t\t\t\t\tcurrentPage = endPage + 1;\r\n");
      out.write("\t\t\t\t\t\tstart = (currentPage-1) * pageSIZE +1;\r\n");
      out.write("\t\t\t\t\t\tend = currentPage * pageSIZE;\r\n");
      out.write("\t\t\t\t\t\tgetListStd();\r\n");
      out.write("\t\t\t\t\t\tpaging();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tgetListStd();\r\n");
      out.write("\t\t\tpaging();\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*$(window).scroll(function() {\r\n");
      out.write("\t\t\t\tvar win = $(window)\r\n");
      out.write("\t\t\t\tvar scrollHeight = win.scrollTop() + win.height();\r\n");
      out.write("\t\t\t\tvar documentHeight = $(document).height();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (documentHeight <= scrollHeight + 300) {\r\n");
      out.write("\t\t\t\t\tlist();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t  <script src=\"js/plugins/plugins.js\"></script> \r\n");
      out.write("\t  <script src=\"js/assan.custom.js\"></script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/listStd.jsp(119,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginVo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        \t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        \t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/listStd.jsp(121,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.role eq 'customer' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t\t\t<a id=\"SNS\" class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"snsMyPageView.do?cust_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&provider_no=-1\" >SNS</a>\r\n");
          out.write("                        \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t\t\t<a id=\"SNS\" class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"snsMyPageView.do?cust_no=-1&provider_no=-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >SNS</a>\t\r\n");
          out.write("                        \t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/listStd.jsp(129,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginVo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t<a class=\"nav-link\" aria-haspopup=\"true\" aria-expanded=\"false\" href=\"login\" >SNS</a>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/listStd.jsp(156,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginVo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"nav-item dropdown user-dropdown align-items-center\" >\r\n");
          out.write("                                    <a class=\"nav-link\" href=\"#\" id=\"dropdown-user\" role=\"button\"\r\n");
          out.write("                                       data-toggle=\"dropdown\">\r\n");
          out.write("                                <span class=\"user-states states-online\">\r\n");
          out.write("                                    <img src=\"cust_img/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.cust_img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"35\" alt=\"\" class=\" img-fluid rounded-circle\">\r\n");
          out.write("                                </span>\r\n");
          out.write("                                        <span class=\"ml-2 h-lg-down dropdown-toggle\">\r\n");
          out.write("                                                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.nick_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                        </span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                    <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdown-user\" style=\"background-color: #212121!important\" >\r\n");
          out.write("                                        <a class=\"dropdown-item\" href=\"profile\"><i class=\"icon-User\"></i>My Profile</a>\r\n");
          out.write("                                        ");
          if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        <!--추가하면 되는 부분  -->\r\n");
          out.write("                                        <a class=\"dropdown-item\" href=\"logout\"><i class=\"icon-Power\"></i>\r\n");
          out.write("                                            Log Out</a>\r\n");
          out.write("\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                </li>\r\n");
          out.write("                                <li class=\"h-lg-up nav-item\">\r\n");
          out.write("                                    <a href=\"#\" class=\" nav-link collapsed\" data-toggle=\"collapse\"\r\n");
          out.write("                                       data-target=\"#navbarToggler\" aria-expanded=\"false\">\r\n");
          out.write("                                        <i class=\"icon-Magnifi-Glass2\"></i>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        \t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        \t");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/views/listStd.jsp(170,41) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.role eq 'customer' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        \t\t <a class=\"dropdown-item\" href=\"custMyPage?cust_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><i class=\"icon-User\"></i>고객 My Page</a>\r\n");
          out.write("                                        \t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        \t\t<a class=\"dropdown-item\" href=\"provMyPageView.do?cust_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><i class=\"icon-User\"></i>사업자 My Page</a>\r\n");
          out.write("                                        \t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                           \t\t<li><a href=\"login\"><font style=\"color: #F4923D\">Join Us</font></a></li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }
}
